### ISSUE TITLE
Borders around Firefox location and search entry boxes are Black

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#35]
As seen in the attatched screen shot the borders around Firefox location and search entry boxes are black when unselected but they should be `#A8A8A8`
- Running MATE 1.16.0 and GTK 3.20.9 on Ubuntu MATE 16.10 daily
- Affects Ambiant-MATE and Radiant-MATE

![firefox_black_borders_on_location_and_search](https://cloud.githubusercontent.com/assets/304639/19096137/27f2136e-8a92-11e6-8a45-be7313d41d5a.png)

**Comment by raveit65** [comment]
This is a really stupid issue as ff ignored gtk3-inspector.

**Comment by raveit65** [comment]
The border color can be set with
frame {
    border-width: 1px;
    border-style: solid;
    border-color: shade (@bg_color, 0.82);
}

But 'frame' is everywhere in the code of any app, i result you will see borders where you don't want to see them, eg. statusbar of caja.
I suggest to forward this issue ff.

Btw. the bg is set with the .view style class which is bad too.

**Comment by flexiondotorg** [comment]
Yeah, creating a `frame` messes up a great deal of things.

**Comment by flexiondotorg** [comment]
Just to be clear, I agree there is nothing more to be done about this for now :-) Will require upstream attention as I can't find a theme that isn't affected by this issue.

**Comment by lukefromdc** [comment]
I managed to use a long widget chain to control this in UbuntuStudio_Legacy and either I have not hit any other matches from it or the use of the theme background color at a 1px width is sucesfully hiding it in all other cases:

```
/*Firefox 49 is a broken mess in GTK 3.20 or later and needs this */
/*Let's exclude as many unwanted matches as possible and if that fails keep it subtle*/

window.background>widget>:not(widget):not(box):not(tab):not(notebook):not(stack):not(frame)>scrolledwindow.frame {
	border-style: solid;
	border-color: @theme_bg_color;
	border-width: 1px;
}
```

**Comment by raveit65** [comment]
Hmm, in my tests with ff-0.48 in ubuntu it was the the frame selector w/o a dot, so called **css name** or **node**. With a dot it is a so called a **style class** which is saved to use with most themes, because here the border is already themed.
https://github.com/flexiondotorg/ubuntu-mate-themes/blob/master/usr/share/themes/Ambiant-MATE/gtk-3.0/gtk-widgets.css#L805
Maybe this is changed with ff-0.49.

With Menta/Submarine themes i did a mistake in early 3.20 port. Here i used a border for 'frame' **css name**. The result was i had to remove the border at a lot of unwanted places.
Worst place was nemo's desktop window.
Anyway with those themes the border color is correct, but i don't like to do this mistake again. 

The easiest fix would be if ff devs add a style class on top of firefox, like .mozilla-container ;)
Then they can do what they want and theme artist can add settings which only match ff.
Mandatory for a big and important application like ff.

**Comment by raveit65** [comment]
With ff-49 it is also the css name frame.
@flexiondotorg 
You can test this for yourself
```
/* wtf setting for firefox */
frame {
    border-width: 1px;
    border-style: solid;
    border-color: shade (@bg_color, 0.82);
}

/* override for wtf */
statusbar > frame, /* caja, pluma, etc. */
GvcMixerDialog frame { /* Mate Mixer dialog */
    border-width: 0px;
    border-style: none;
}
```
But i'm pretty sure there are more applications where we need the override.

**Comment by flexiondotorg** [comment]
Yep, I had a quick test. The above is certainly a great start. I've refined it slightly.

```
/* wtf setting for firefox */
frame {
    border-width: 1px;
    border-style: solid;
    border-color: shade (@bg_color, 0.82);
}

/* override for wtf */
box > frame, /* mate-tweak */
statusbar > frame, /* caja, etc. */
statusbar > widget > frame, /* pluma */
GvcMixerDialog frame { /* Mate Mixer dialog */
    border-width: 0px;
    border-style: none;
}
```

**Comment by lukefromdc** [comment]
I was using scrolledwindow.frame because the exact place I had a problem in my theme was the text entry fields that could have scrollbars if enough was inside use that selector and were getting no border at all, causing them to have no visible boundary if the website set a white background behind them.  Using frame also worked but I wanted to limit the impact on anything else as much as possible.

This nastiness is going to be on a per-theme basis until Firefox either properly supports GTK 3.20+ or gains support for a userChrome.css file inside the theme directory.

**Comment by flexiondotorg** [comment]
@raveit65 This issue has resurfaced in Ubuntu MATE 17.04 running Firefox 50. None of the previous workaround appears to work, there is also this bug report on Launchpad:

  * https://bugs.launchpad.net/ubuntu-mate/+bug/1662262

It is important to note that the Ambiance and Radiance themes, available via `apt install light-themes`, work correctly.
