### ISSUE TITLE
Download progress bars are missing from Firefox

### ISSUE THREAD

**Issue by flexiondotorg** [flexiondotorg/ubuntu-mate-themes#41]
As seen in the attached screen shot, when using Ambiant-MATE and Radiant-MATE the download progress bars are missing in Firefox.  *By comparison Ambiance and Radiance do have download progress bar in Firefox*. 

  * Running MATE 1.16.0 and GTK 3.20.9 on Ubuntu MATE 16.10 daily
  * Affects Ambiant-MATE and Radiant-MATE

## Ambiant-MATE (incorrect)

![ff_download_progress_ambiant-mate_1](https://cloud.githubusercontent.com/assets/304639/19174259/5ed4bc08-8c25-11e6-8518-bdc814016360.png)

![ff_download_progress_ambiant-mate_2](https://cloud.githubusercontent.com/assets/304639/19174261/631a3d6a-8c25-11e6-98e7-fef36a80b1d3.png)

## Ambiance (correct)

![ff_download_progress_ambiance_1](https://cloud.githubusercontent.com/assets/304639/19174264/69c920cc-8c25-11e6-9cd4-10f56d9ea484.png)

![ff_download_progress_ambiance_2](https://cloud.githubusercontent.com/assets/304639/19174269/6f5a5038-8c25-11e6-9e6e-ae7395c9b31a.png)

**Comment by raveit65** [comment]
Please try https://github.com/flexiondotorg/ubuntu-mate-themes/commit/13b88606725c2d1ded4734cc0b1f0a42a4db6b0a
Firefox use simply old 3.18 css syntax.

Note: I don't get this issue with ff-49 in fedora f24, probably fixed by upstream or a fedora patch.
http://pkgs.fedoraproject.org/cgit/rpms/firefox.git/tree/?h=f24

**Comment by flexiondotorg** [comment]
Confirmed as working. Thank you! :-)
